artifacts_root: artifacts # root folder for all artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion # data ingestion folder will be created under artifacts after running the code`
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip # local path where the downloaded data will be stored
  unzip_dir: artifacts/data_ingestion # directory where the data will be unzipped


data_validation:
  root_dir: artifacts/data_validation # data validation folder will be created under artifacts after running the code
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv # directory where the data will be unzipped
  STATUS_FILE: artifacts/data_validation/status.txt # status file to track the validation status

data_transformation:
  root_dir: artifacts/data_transformation # data transformation folder will be created under artifacts after running the code
  data_path: artifacts/data_ingestion/winequality-red.csv # path to the data file











